# Generated by Django 5.1.1 on 2024-11-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_onetimepassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onetimepassword',
            name='token',
        ),
        migrations.AddField(
            model_name='onetimepassword',
            name='otp_code',
            field=models.CharField(default=None, max_length=6),
            preserve_default=False,
        ),
    ]
