# Generated by Django 5.1.1 on 2024-12-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_Added_is_verified_and_used_correct_parameter_data_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscription_status',
            field=models.CharField(default='free', max_length=10),
        ),
    ]
