# Generated by Django 5.1.1 on 2025-01-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_subscription_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Profile Image URL'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired')], max_length=10),
        ),
    ]
