# Generated by Django 5.1.1 on 2024-10-05 08:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_tasks_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottask',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bottask',
            name='execution_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bottask',
            name='owner',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
