# Generated by Django 5.1.1 on 2024-10-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_tasks_api', '0002_bottask_created_bottask_execution_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottask',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
