# Generated by Django 5.1.1 on 2024-10-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_tasks_api', '0003_alter_bottask_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottask',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
