# Generated by Django 5.1.1 on 2024-10-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_tasks_api', '0004_alter_bottask_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bottask',
            options={'verbose_name': 'Bot Task 😁', 'verbose_name_plural': 'Bot Tasks 😈'},
        ),
        migrations.AlterField(
            model_name='bottask',
            name='owner',
            field=models.CharField(max_length=50, verbose_name='Owner(API Key)'),
        ),
        migrations.AlterField(
            model_name='bottask',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='Task Title'),
        ),
    ]
